### ISSUE TITLE
Stuck on sample loading stage. (during training) 

### ISSUE THREAD

**Issue by mesz0r** [iperov/DeepFaceLab#5313] opened 2021-04-20 13:04 UTC
When I start training with "Quick96", everything freezes at the samples loading stage. What could be the problem? How to fix it?

![image](https://user-images.githubusercontent.com/42600969/115400386-e53b6f80-a1f1-11eb-961a-d497c4d99ad6.png)

**Comment by 00ar06** [comment] 2021-05-05 18:49
Hi, Im having exactly the same problem too. Did you manage to fix it? Thanks

**Comment by messorstruktor** [comment] 2021-05-05 18:51
> Hi, Im having exactly the same problem too. Did you manage to fix it? Thanks

No, I'm still looking for how to fix this too. @00ar06

**Comment by 00ar06** [comment] 2021-05-05 19:02
Ahh ok, I haven’t seen this issue many other places so far. Might post it on a Few forums to try and get some answer.

**Comment by messorstruktor** [comment] 2021-05-05 19:19
> Ahh ok, I haven’t seen this issue many other places so far. Might post it on a Few forums to try and get some answer.

That would be great, I've tried everything to fix it. I have no idea what caused this error, everything works fine on older computers. And what is most interesting, I already used DeepFaceLab on this computer around 2019-2020, everything was fine. ¯\_(ツ)_/¯

**Comment by 00ar06** [comment] 2021-05-06 00:06
Oh right that’s odd if you had it working before. I actually got mine to work. Well upto a point before. Basically, I checked the change log in the files and it opened to a website. Here it mentioned about if you have Windows 10 you’d need to go to setting, display, graphic settings and then you had to click yes to boosting performance. I can check tomorrow what exactly the names of the things were as I’m away from my computer. But once I did this, is went past the loading phase and began to train. However, now I’m at the stage of merging, but having issues there now too. I’ve been getting this error “paging file is too small for operation to complete” . So not too sure what to do now. Maybe check the above fix for yourself, hopefully it works👍

**Comment by messorstruktor** [comment] 2021-05-06 08:18
> Oh right that’s odd if you had it working before. I actually got mine to work. Well upto a point before. Basically, I checked the change log in the files and it opened to a website. Here it mentioned about if you have Windows 10 you’d need to go to setting, display, graphic settings and then you had to click yes to boosting performance. I can check tomorrow what exactly the names of the things were as I’m away from my computer. But once I did this, is went past the loading phase and began to train. However, now I’m at the stage of merging, but having issues there now too. I’ve been getting this error “paging file is too small for operation to complete” . So not too sure what to do now. Maybe check the above fix for yourself, hopefully it works👍

Yes, the problem is what you described. I think that this mode disappeared after reinstalling Windows. I set the performance mode, but then the same error as yours. The paging file I have is 30GB, maybe 16GB of RAM is not enough for work? But it worked before. Thanks for helping me with this, but what to do next remains a mystery.

**Comment by 00ar06** [comment] 2021-05-06 11:07
Ah no problem, well at least were both at the same place now 😂 hmm yeah, I’ll have to have a look at the paging file thing today. I’m very new to this, can you check your paging file in the settings?

**Comment by FrogMaster-jpg** [comment] 2021-05-22 19:57
Both of you have the same issue I am constantly getting suck on as well. I have been trying to do lots of research but have not been able to figure anything out yet. Whenever I try to train using Quick96, the process hangs when trying to run the second loading samples. I'm not sure what is going on? 🙁

**Comment by Cioscos** [comment] 2021-10-06 16:10
Try to increase or enable paging file.

**Comment by RUGMJ7443** [comment] 2021-10-06 16:20
just turned on the gpu boosting setting in windows i now get an error which seems like it hasnt got enough ram [error](https://pastebin.com/yeKrgLwU)

**Comment by dausdanger** [comment] 2022-01-10 02:29
anyone has solved this problem?

**Comment by messorstruktor** [comment] 2022-01-10 05:31
> anyone has solved this problem?

Nope :(

**Comment by ThoBur** [comment] 2022-02-21 17:17
I had the same problem and increased my paging file to 64gb. After a reboot it worked. The paging file is using 60GB during the process.

Thx

**Comment by salva133** [comment] 2022-05-07 22:54
Why does'nt it just simply use the RAM instead of the paging file? I simply cannot provide 60GB from my boot partition and if I activate the paging file on my other SSD DFL does not care.

**Comment by PH2100** [comment] 2023-01-29 15:40
Is there a solution to this already? I read in a other post, that they downgraded to GPU drivers from 2021 and that fixed it. Haven't tried it myself tho

**Comment by ghost** [comment] 2023-06-08 22:39
Did you ever find the answer? If so, would you mind sharing it and closing this issue?

**Closed** 2023-09-08 12:21 UTC
