### ISSUE TITLE
GeForce RTX 3090 doesnt work XSeg train

### ISSUE THREAD

**Issue by PeiCinh** [iperov/DeepFaceLab#965] opened 2020-12-06 11:10 UTC
Run Xseg train , it always stop this view and not update ,

Using 141 segmented samples.
============= Model Summary =============
==                                     ==
==        Model name: XSeg             ==
==                                     ==
== Current iteration: 1                ==
==                                     ==
==----------- Model Options -----------==
==                                     ==
==         face_type: wf               ==
==        batch_size: 16               ==
==                                     ==
==------------ Running On -------------==
==                                     ==
==      Device index: 0                ==
==              Name: GeForce RTX 3090 ==
==              VRAM: 24.00GB          ==
==                                     ==
=========================================
Starting. Press "Enter" to stop training and save model.
[19:07:51][#000002][3865ms][0.6886]

Driver: 457.51
 CUDA 11.2
CUDNN 11.1

**Comment by kogereneliteness** [comment] 2020-12-07 20:37
Hello

I have the same problem. Geforce 3080 10GB does not train more than a few iterations.
I tried my best to debug and it completes a few iterations but stops in this call: model.train_one_iter() and never finishes.

Few things to note:
1. When loading XSEG on a Geforce 3080 10GB it uses ALL the VRAM. I have to lower the batch_size to 2, to have it even start. I used to run XSEG on a Geforce 1060 6GB and it would run fine at batch 8. 

Could this be some VRAM over allocation problem?

2. Also worth of note, CPU training works fine.

GPU: Geforce 3080 10GB.
Tensorflow-gpu  2.4.0rc3
Driver 457.51
CUDA 11.1
CUDNN 11.1
OS: Windows 10 20H2

DFL build, is the latest RTX 3000 build with the "_internal\DeepFaceLab" folder mirrored from latest github comit and latest CUDNN .dll files.

**Comment by PeiCinh** [comment] 2020-12-08 11:36
> Hello
> 
> I have the same problem. Geforce 3080 10GB does not train more than a few iterations.
> I tried my best to debug and it completes a few iterations but stops in this call: model.train_one_iter() and never finishes.
> 
> Few things to note:
> 
> 1. When loading XSEG on a Geforce 3080 10GB it uses ALL the VRAM. I have to lower the batch_size to 2, to have it even start. I used to run XSEG on a Geforce 1060 6GB and it would run fine at batch 8.
> 
> Could this be some VRAM over allocation problem?
> 
> 1. Also worth of note, CPU training works fine.
> 
> GPU: Geforce 3080 10GB.
> Tensorflow-gpu 2.4.0rc3
> Driver 457.51
> CUDA 11.1
> CUDNN 11.1
> OS: Windows 10 20H2
> 
> DFL build, is the latest RTX 3000 build with the "_internal\DeepFaceLab" folder mirrored from latest github comit and latest CUDNN .dll files.

I follow ur way about batch_size to 2 . But it still can't work. I try use cpu to run Xseg train , it can worki

**Comment by iperov** [comment] 2020-12-11 17:26
it is a TF2.4.0 issue.

Current 2080TI build based on tf 2.3.1 works fine.

**Comment by kogereneliteness** [comment] 2020-12-12 11:53
Thanks for the reply sir.

So would this issue be auto resolved once the TF 2.4 is released as a stable release?

Did you see that TensorFlow 2.4.0 adds support for TF32 format for Ampere based GPUs; it is enabled by default. Does Deepfacelab support this, without any code changes?

**Comment by iperov** [comment] 2020-12-12 14:08
> So would this issue be auto resolved once the TF 2.4 is released as a stable release?

it is not gauranteed.
TF is a shit last years.

**Comment by marsmana** [comment] 2020-12-13 04:25
This problem can be solved, but sometimes it recurs. 

you should use CUDA11.1 files to replace the files in CUDA folder. If the file under CUDA is _10 and cudA11.1 is _11, rename _11 to _10 and replace the file.

The Cudnn folder is also processed this way.

refer to cuda11.1 release node : Enhanced CUDA compatibility across minor releases of CUDA will enable CUDA applications to be compatible with all versions of a particular CUDA major release.

the legacy is that DFL may stuck, when the GPU’s cuda is fully loaded.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iperov** [comment] 2020-12-13 04:41
@marsmana I checked, it does not fix the problem.

**Comment by iperov** [comment] 2020-12-13 04:48
but I will check cuda 11.1.1 ...

**Comment by marsmana** [comment] 2020-12-13 04:57
>@marsmana I checked, it does not fix the problem.

@iperov  I didn't install CUDa and CUDnn. Does this make such a difference?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iperov** [comment] 2020-12-13 04:59
Checked 11.1.1  . Same it does not fix the problem with tf2.4.0rc4

**Comment by iperov** [comment] 2020-12-13 05:00
tf2.4.0rc4 is just a super buggy shit.
I doubt they will fix the problem.

**Comment by iperov** [comment] 2020-12-13 07:15
@marsmana can you give me access to your comp? I want to test something. Telegram me @iperov

**Comment by iperov** [comment] 2020-12-13 10:31
nevermind, will test on other comp

**Comment by gytters** [comment] 2020-12-13 12:54
Got the same issues on rtx3090 with xseg

**Comment by iperov** [comment] 2020-12-13 12:56
@gytters I know about the problem. It is reproducable. But it is an tensorflow issue. Because the same code on tf 2.3.1 works fine.

**Comment by kogereneliteness** [comment] 2020-12-13 14:55
Anyone else notice that XSEG on the TF 2.4 seems to use insane amounts of VRAM. Even though XSEG does not complete a iteration. I have to use batch size 2 on a Geforce 3080 10GB. I used to be able to start XSEG with batch size 8 with only 6GB ram on a 1060 card. 

I wonder if this is related. Perhaps a VRAM allocation error in TF 2.4?

**Comment by marsmana** [comment] 2020-12-14 08:06
some report says Hardware-accelerated GPU scheduling, which is in “ default graphics setting ”, can solve the problem. 
I have test it, it works.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iperov** [comment] 2020-12-14 08:14
@marsmana what is this?

**Comment by marsmana** [comment] 2020-12-14 08:19
A setting of win10.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iperov** [comment] 2020-12-14 08:19
wow really works. Thank you very much.

**Comment by kogereneliteness** [comment] 2020-12-14 09:22
Thank you so much it works, not optimal, but works..  

Xseg with 64 samples and batch size of 2, still used 9,7 GB of VRAM? So something is still funky with TF 2.4. 

If i try to run Xseg with batch 8, like my old Geforce 1060 6GB could run, i get OOM's in the tensorflow.

**Comment by iTaKK** [comment] 2020-12-14 21:49
That's strange, my XSEG can run batch 14 on a 3070.

**Comment by kogereneliteness** [comment] 2020-12-15 09:17
> That's strange, my XSEG can run batch 14 on a 3070.

Hmm, how much VRAM does it use then? Mine is using all 10GB.

**Comment by marsmana** [comment] 2020-12-15 09:21
>Thank you so much it works, not optimal, but works..   ...

@kogereneliteness You can try my method above: replace all CUDA and CUDNN files.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kogereneliteness** [comment] 2020-12-15 22:39
@marsmana, It works. XSEG trains on my system with batch 12 now. 
 I replaced the _internal\CUDA and _internal\CUDNN dlls with the following versions.

CUDA 11.1.47
CUDNN 11.1 - v8.0.5.39

Also as a added bonus, my VRAM is 30% lower when training SAEHD.

@iperov Tagging you FYI. It seems the current RTX build needs updated dll files. The one downloaded from MEGA is not optimal with the old CUDA10 dlls.

**Comment by iTaKK** [comment] 2020-12-15 22:52
> 
> 
> > That's strange, my XSEG can run batch 14 on a 3070.
> 
> Hmm, how much VRAM does it use then? Mine is using all 10GB.

7927 MB out of 8GB
I'm using the build from mega, didn't update any of the .dll files.

**Comment by iperov** [comment] 2020-12-16 01:37
@kogereneliteness 

>  It seems the current RTX build needs updated dll files. 

you reverted setting "Hardware-accelerated GPU scheduling" back to off before testing ?

**Comment by kogereneliteness** [comment] 2020-12-16 07:07
@iperov 
> did you revert setting "Hardware-accelerated GPU scheduling" back to off before testing ?

Well it was a 2-part soluition for me. 

Part 1 was enabing the GPU scheduling, that allowed me to train on batch size 2 XSEG, before, it would not complete a iteration and freeze.

Then part 2 updating the CUDA and CUDNN files allowed me to have a normal VRAM usage.

If you want, I can test with GPU scheduling to disabled?

**Comment by iperov** [comment] 2020-12-16 07:18
@iperov
if the dll update does not fix training freeze without "Hardware-accelerated GPU scheduling" fix, then it makes no sense

**Comment by marsmana** [comment] 2020-12-16 08:11
>@iperov  ...

@kogereneliteness Yes, these two parts together constitute a complete solution.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gytters** [comment] 2020-12-16 08:14
> > @iperov  ...
> 
> @kogereneliteness Yes, these two parts together constitute a complete solution.
> 
> Sent with [GitHawk](http://githawk.com)

Well , it doesn’t make use of all the recourses of the 3090 with the window graphics settings activated

**Comment by kogereneliteness** [comment] 2020-12-16 10:46
@gytters 
> Well , it doesn’t make use of all the recourses of the 3090 with the window graphics settings activated

Perhaps your model is not that demanding. If you increase the batch size, it should be able to use all the resources. (atleast the VRAM).

**Comment by kogereneliteness** [comment] 2020-12-16 10:49
> @kogereneliteness
> if the dll update does not fix training freeze without "Hardware-accelerated GPU scheduling" fix, then it makes no sense

@iperov 

Thanks for the reply.

Without Hardware-accelerated GPU scheduling. Xseg does not train for me. Both with new and old dll's.

But with replaced DLLs i get less VRAM usage. That is a benefit since I can run a bigger batch size or bigger dims or resolution, with more VRAM available. I see that as a good reason to replace the dlls, if possible. But this is just my findings on my system.

**Comment by iperov** [comment] 2020-12-16 10:54
I will release tonight new build with latest tf, cuda, cudnn

**Comment by iperov** [comment] 2020-12-16 14:57
try last build

**Comment by kogereneliteness** [comment] 2020-12-17 08:33
> try last build

@iperov Thanks, it seems VRAM usage is good in the new build. I still depend on "Hardware-accelerated GPU scheduling" enabled. But I don't see any problems with this, everything seems to run pretty good for me now.

Thank you!

**Comment by K0923** [comment] 2020-12-17 13:07
@iperov 
The last version is based on CUDA 11.2 and corresponding cudnn, right? I still got bugs with CUDA 11.1.

**Comment by HappiestCow22** [comment] 2020-12-19 23:29
> @kogereneliteness
> if the dll update does not fix training freeze without "Hardware-accelerated GPU scheduling" fix, then it makes no sense

Just updated windows to test gpu scheduling. Completely fixed it. Using latest build of dfl

**Comment by Zeesy** [comment] 2021-10-04 18:35
Update for 2021: Batch size of 12 running Hardware Acceleration on Win 10 on a GTX 3090 runs fine at ~88% VRAM load.

**Closed** 2021-10-04 18:58 UTC
