### ISSUE TITLE
mask appear at the test output video

### ISSUE THREAD

**Issue by visonpon** [iperov/DeepFaceLab#15] opened 2018-08-16 09:51 UTC
## Expected behavior

*Using the trained model to output faceswapped video, but the video maintain the mask at the bottom of the video.  Hope you can tell me where to uncomment the code or modify it in order to abandon the mask, thanks~*

**Comment by shliang0603** [comment] 2018-12-10 02:57
@visonpon I used the model of MIAEF128， output the images having the mask. Do you  solve the problem?

**Comment by iperov** [comment] 2018-12-10 05:49
@shliang0603 upload your workspace to google drive, provide link, we will check

**Comment by shliang0603** [comment] 2018-12-11 10:37
@iperov Hi,  I have uploaded my workspace to google driver. Can you give me some advice ?

**Comment by iperov** [comment] 2018-12-11 10:38
give me link to download

**Comment by shliang0603** [comment] 2018-12-11 12:03
@iperov Sorry,I forgot it. workspace link is https://drive.google.com/open?id=1VBn8okCp--HngOK2AuN2lAgCSYmcxF_y

**Comment by iperov** [comment] 2018-12-11 12:18
@shliang0603 are you training with jpg images ?

**Comment by iperov** [comment] 2018-12-11 12:19
@shliang0603 jpg images are not allowed.
Also I cannot download folder from google drive. You must ZIP it.

**Comment by iperov** [comment] 2018-12-11 16:13
@shliang0603 I am checking your workspace now...

**Comment by shliang0603** [comment] 2018-12-12 09:05
@iperov 
## Thanks for your answering. I saw the converted video, it's very good. Then I convert it again according to your requirements, but there are still problem.
![image](https://user-images.githubusercontent.com/37186266/49857900-92399c80-fe2e-11e8-9de3-73446ef12198.png)

## In my workspace dictionary have existed extracting images in worksapce/data_dst/aligned
![image](https://user-images.githubusercontent.com/37186266/49857870-85b54400-fe2e-11e8-8ea2-ea424238e613.png)
## `In my worklspace/data_dst/merged dir, Many composite images have shadows.  Can you help me to check what the problem is  `
![image](https://user-images.githubusercontent.com/37186266/49857671-1f302600-fe2e-11e8-88fd-4c35c6b8a441.png)

**Comment by iperov** [comment] 2018-12-12 10:05
Enter digit when choose mode, 1 or 2 , 3 , 4.

Also I have no such artefacts at any modes.
May problem in linux :( I have no linux to support it.

**Comment by iperov** [comment] 2018-12-12 10:44
my 6GB run miaef128 fine.

**Comment by visonpon** [comment] 2018-12-20 01:35
Hi， @shliang0603 sorry i haven't find a solution for this confused question

**Comment by iperov** [comment] 2018-12-20 02:07
this bug is only linux specific. You can do minimal reproduce.

**Closed** 2019-01-10 18:36 UTC
