### ISSUE TITLE
Face extraction doesn't work with GPU

### ISSUE THREAD

**Issue by hayzamjs** [iperov/DeepFaceLab#286] opened 2019-06-20 13:10 UTC
## Expected behavior

Extracting face using GPU(AMD)

## Actual behavior

No extracted face after running for a while, on GPU. But when I run it with CPU with the following parameters(CPU only) it's fine.
```
@echo off
call _internal\setenv.bat

"%PYTHON_EXECUTABLE%" "%DFL_ROOT%\main.py" extract ^
    --input-dir "%WORKSPACE%\data_src" ^
    --output-dir "%WORKSPACE%\data_src\aligned" ^
    --cpu-only ^
    --detector mt ^
    --debug-dir "%WORKSPACE%\data_src\aligned_debug"

pause
```

## Steps to reproduce

I've tried a lot of times to use the GPU but it just gets stuck. Don't know if this occurs to others as well.

## Other relevant information
Using the prebuilt version, trying with a VEGA 64, also tried with an RX560, same result.
This issue looks very much like https://github.com/iperov/DeepFaceLab/issues/277

After I extract faces with the CPU parameters from ^, it works well with the SAE algorithm.

**Comment by kadrim** [comment] 2019-11-24 10:09
looks like a duplicate of #335 for which a fix is ready. But i cannot tell this as the log of the output is missing. Post it here and then check if #501 works for you.

**Closed** 2020-03-28 05:39 UTC
