### ISSUE TITLE
[Linux] Fail to run on Linux without reverting linux fix

### ISSUE THREAD

**Issue by DieselWoodard** [iperov/DeepFaceLab#194] opened 2019-03-16 14:05 UTC
If I try run after straight checkout i get 'TypeError: can't pickle weakref objects'

I saw there was commit for fixin linux, but it seems to be opposite, if I remove 'multiprocessing.set_start_method("spawn")' again from main.py it works.

so unless 296e8a111ad2cdd59e95de468c1220738eb907ba is necessary for windows I think it should be reverted to make it work on windows

**Comment by iperov** [comment] 2019-03-16 14:41
windows works with and without 
`multiprocessing.set_start_method("spawn")`

@lbfs

**Comment by lbfs** [comment] 2019-03-16 16:22
I don't understand why this would break it, let me look into it because I haven't been able to have this issue on my system.

**Comment by lbfs** [comment] 2019-03-16 16:23
Also I'm slightly confused by your issue, you state at the end of your post that you need to revert it to make it work on Windows, but in your title it says Fails to Run on Linux?

**Comment by lbfs** [comment] 2019-03-16 21:29
Check to see if you're using Python 3.7, apparently this is a common error with a lot of libraries on Python 3.7? 

Also might be a good idea to reinstall the requirements-cuda.txt to make sure your on correct versions.

**Comment by lbfs** [comment] 2019-03-19 19:00
@DieselWoodard Hello?

**Comment by TheFeelTrain** [comment] 2019-03-21 22:53
I have the same issue. Removing that line fixed it for me as well.

**Comment by iperov** [comment] 2019-03-21 22:57
ROFL
i can remove
`multiprocessing.set_start_method("spawn")`
this never affect windows.

**Comment by iperov** [comment] 2019-03-21 22:59
But I will not write python code for different versions of linux. This breaks the paradigm of python.

**Comment by lbfs** [comment] 2019-03-21 23:22
Can you please tell me what version of Python you're using and what operating system you are using @TheFeelTrain . I can't suddenly have a magical fix without knowing additional information.

**Comment by lbfs** [comment] 2019-03-22 00:01
The only reason I think this could fail is if you're launching it from another application, like Jupyter Notebook, which is setting a spawn mode of fork. 

But this fix is required for the program to work, as detailed here https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods which shows that Linux and Windows share different default multiprocess logic so it needs to be defined as which one is being used. 

All Linux distros should default to fork, which is why I know this shouldn't have anything to do with the issues encountered.

**Comment by TheFeelTrain** [comment] 2019-03-22 01:25
Yeah the extractor fails without the line now. I'm not home but off the top of my head it's Arch Linux, all python dependencies are the same version as in the requirements-cuda.txt, and it's python 3.7.2 from the official Arch repos.

**Comment by lbfs** [comment] 2019-03-22 01:45
I have a feeling this is related to Python 3.7.2 because I've read about similar errors caused in Python 3.7.

**Comment by TheFeelTrain** [comment] 2019-03-22 02:06
I will try downgrading to 3.6 when I get back home and I'll let you know how it goes.

**Comment by lbfs** [comment] 2019-03-22 06:14
Can confirm that using the Anaconda installation instructions should work on Arch Linux after testing, you will need to make sure your newest video drive is installed and that you've installed ffmpeg, cmake, git, and probably gcc. https://github.com/lbfs/DeepFaceLab_Linux/blob/master/README.md 

I'm not having luck setting up a stable Python3.7 environment, but I'll look more into it later this weekend when I have time.

**Comment by lbfs** [comment] 2019-03-22 18:56
Full traceback on Python 3.7
```python
Traceback (most recent call last):
  File "/mnt/secondary/DeepFaceLab_Linux/mainscripts/Trainer.py", line 78, in trainerThread
    loss_string = model.train_one_iter()
  File "/mnt/secondary/DeepFaceLab_Linux/models/ModelBase.py", line 360, in train_one_iter
    sample = self.generate_next_sample()
  File "/mnt/secondary/DeepFaceLab_Linux/models/ModelBase.py", line 357, in generate_next_sample
    return [next(generator) for generator in self.generator_list]
  File "/mnt/secondary/DeepFaceLab_Linux/models/ModelBase.py", line 357, in <listcomp>
    return [next(generator) for generator in self.generator_list]
  File "/mnt/secondary/DeepFaceLab_Linux/samples/SampleGeneratorFace.py", line 58, in __next__
    return next(generator)
  File "/mnt/secondary/DeepFaceLab_Linux/utils/iter_utils.py", line 55, in __next__
    self.p.start()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/usr/lib/python3.7/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle weakref objects
Done.
```

**Comment by lbfs** [comment] 2019-03-23 02:58
A temporary workaround I found for Python 3.7 is to change in SampleGeneratorFace.py
``self.generators_count = min ( generators_count, len(self.samples) )``
to 
``self.generators_count = 1``

I'm not really sure what a proper fix would be because I don't fully understand the issue occuring, but outside of that TF 1.12 (custom build) / python37 / cuda 10 configuration works

**Comment by lbfs** [comment] 2019-03-24 20:30
![out](https://user-images.githubusercontent.com/47072419/54885397-a5a2cd80-4e49-11e9-9441-a7437c82d374.png)

Reproducible in Windows Python 3.7, multiprocessing fix has nothing to do with this issue, already removed it to test.

**Comment by iperov** [comment] 2019-03-25 06:30
but I dont support 3.7

**Comment by lbfs** [comment] 2019-03-25 06:32
I'm trying to support versions to match as closely to your build, so I suggest 3.6 on my fork, but this is the cause of the error this person got. Just wanted to do investigating into it.

**Comment by iperov** [comment] 2019-03-25 06:38
sorry, I am closing issues in DFL repo.
There is too much flood from newbie users, that cannot search manuals or tutorials and asking lame questions.

**Comment by iperov** [comment] 2019-03-26 05:20
but decided not to close forever 
just unwatched repo, let newbies flood this repo :D

**Comment by DieselWoodard** [comment] 2019-04-03 17:21
Sorry I didn't respond earlier, these are the versions:

python-tensorflow-opt-cuda 1.13.1-4
Python 3.7.3
cuda 10.1.105-6
cudnn 7.5.0.56-1

And it works well, as long as I remove `multiprocessing.set_start_method("spawn")`

And I use iperovs repo, it works well on linux too, with that line removed.

And sorry for confusing you, I only have linux, my comment was that I thought windows might not work if that line was removed.

**Closed** 2019-04-11 09:34 UTC
