### ISSUE TITLE
Continue convert

### ISSUE THREAD

**Issue by wasyleque** [iperov/DeepFaceLab#339] opened 2019-08-10 11:13 UTC
Is it possible to create a script to continue convert files with alpha ? 
(many times script is breaking when two faces are on the same frame in aligned DIR).
It wouild be helpfull to continue, not convert from beginning.

**Comment by Auroir** [comment] 2019-08-11 19:32
(OP is stating that when you use export with alpha and a frame has more than 1 face to swap in it, DFL errors out when processing the 2nd face. It throws an error about adding another channel to a 4 channel image.)

Yes, this is currently a problem. It's uncommon for people to swap more than one face per frame so I imagine it's low priority. 

If I remember correctly the problem exists because when the system makes an alpha image it directly adds the alpha channel to the existing frame. If there's more than one face in the frame then there's going to be an alpha channel in the image when processing the 2nd face. Since it can't add another channel to a RGBA image it errors out. The obvious fix might be summing the alpha channels together if one already exists. This seems too easy though, I suspect merging/color-transfer/etc. makes it more difficult than it appears. 

This is on my TODO. I want this feature fixed/expanded as well since I export with alpha in all my projects, I'll push a patch if I end up fixing it.

**Comment by Auroir** [comment] 2019-08-18 06:44
Duplicate of #354

**Closed** 2020-03-28 05:41 UTC
