### ISSUE TITLE
Error：nnlib.pynvml.NVMLError_Uninitialized: Uninitialized

### ISSUE THREAD

**Issue by shliang0603** [iperov/DeepFaceLab#154] opened 2019-02-19 01:18 UTC
# Error：nnlib.pynvml.NVMLError_Uninitialized: Uninitialized
> when I extract face, the following error occurs. Can you give me some advice ? 

 mosheng@server:~/work2/project/shliang/2_DeepFaceLab_20190217$ python main.py extract --input-dir workspace/data_dst/ --output-dir test/ --detector mt --multi-gpu
Running extractor.

Performing 1st pass...
Running on GeForce GTX 1080 Ti #0.
Running on GeForce GTX 1080 Ti #1.
Exception while initialization: Traceback (most recent call last):
  File "/data2/work/project/shliang/2_DeepFaceLab_20190217/utils/SubprocessorBase.py", line 225, in subprocess
    fail_message = self.onClientInitialize(client_dict)
  File "/data2/work/project/shliang/2_DeepFaceLab_20190217/mainscripts/Extractor.py", line 269, in onClientInitialize
    device_config = nnlib.DeviceConfig ( cpu_only=self.cpu_only, force_gpu_idx=self.device_idx, allow_growth=True)
  File "/data2/work/project/shliang/2_DeepFaceLab_20190217/nnlib/devicelib.py", line 50, in __init__
    gpu_idx = force_gpu_idx if (force_gpu_idx >= 0 and devicelib.isValidDeviceIdx(force_gpu_idx)) else devicelib.getBestDeviceIdx() if not choose_worst_gpu else devicelib.getWorstDeviceIdx()
  File "/data2/work/project/shliang/2_DeepFaceLab_20190217/nnlib/devicelib.py", line 153, in isValidDeviceIdx
    return (idx < nvmlDeviceGetCount())
  File "/data2/work/project/shliang/2_DeepFaceLab_20190217/nnlib/pynvml.py", line 799, in nvmlDeviceGetCount
    _nvmlCheckReturn(ret)
  File "/data2/work/project/shliang/2_DeepFaceLab_20190217/nnlib/pynvml.py", line 310, in _nvmlCheckReturn
    raise NVMLError(ret)
nnlib.pynvml.NVMLError_Uninitialized: Uninitialized

**Comment by iperov** [comment] 2019-02-19 09:58
I dont support linux.
May be @lbfs can help you.

**Comment by lbfs** [comment] 2019-02-19 18:31
I've fixed this in my fork.

**Comment by shliang0603** [comment] 2019-02-22 01:23
@lbfs  Can you tell me how to solve the problem

**Comment by HelpSeeker** [comment] 2019-02-23 15:35
@shliang0603 You can compare lbfs's fork with the original repo: https://github.com/iperov/DeepFaceLab/compare/master...lbfs:master
In this particular case look up what was changed in nnlib/device.py

**Comment by lbfs** [comment] 2019-03-13 08:45
I've been trying to find a proper fix for this, because the current fix feels like a hack. 
Right now, in order to get this error to go away you need to recall nvmlInit() either in functions themselves or the method I've implemented where it is called in Config() 

For whatever reason, even though the original nvmlInit() works in the bottom of the device.py and the device functions right after work, once we return to DeviceConfig everything falls apart and breaks until nvmlInit() is called again. 

Heres the small fix I implemented to make something work
https://github.com/lbfs/DeepFaceLab_Linux/commit/80c3d53650c858fe08a15adebecb41d536e7f566

I'd really like to figure out a proper fix, but attempting to debug this in Visual Studio Code, it actually works there momentarily, but then the entire program hangs in an infinite loop.

**Comment by iperov** [comment] 2019-03-13 09:21
> original nvmlInit() works in the bottom of the device.py 

you are wrong. 
nvmlInit() called on device.py import before any `devicelib.function` call

**Comment by iperov** [comment] 2019-03-13 09:22
also subj code is outdated

**Comment by lbfs** [comment] 2019-03-13 11:25
Yeah I understand that nvmlInit() is called before any of the devicelib.function calls. 

https://github.com/lbfs/DeepFaceLab_Linux/commit/c9af42c43622ba3a76d5ff87592f90c1e5cea99e

The issue being experienced seems odd, considering this works on Windows without much problem. I've attached a better fix I'm using in my repository now, but I still don't think it's the best fix to be using. I'll have to look more into it when I have time. At least it allows all the extractors to be usable.

**Comment by iperov** [comment] 2019-03-13 11:28
may be this is a python problem?
python should to run device.py code on subprocess start

**Comment by lbfs** [comment] 2019-03-13 11:31
I mean possibly, I don't know what the difference would be. The code does seem to be ran on import, just the places it can be accessed seemed to be reduced compared to Windows.

**Comment by iperov** [comment] 2019-03-13 11:32
write print()s in device.py around initialization and check

**Comment by lbfs** [comment] 2019-03-13 11:50
In device.py
```python
if device.backend is None and not force_tf_cpu:
    #first trying to load NVSMI and detect CUDA devices for tensorflow backend,
    #even force_plaidML is choosed, because if plaidML will fail, we can choose tensorflow
    try:
        nvmlInit()
        has_nvml = True
        device.backend = "tensorflow"   #set tensorflow backend in order to use device.*device() functions
        
        gpu_idxs = device.getAllDevicesIdxsList()
        gpu_caps = np.array ( [ device.getDeviceComputeCapability(gpu_idx) for gpu_idx in gpu_idxs ] )
        
        print(gpu_idxs)
        print(gpu_caps)
        print([ (i, nvmlDeviceGetName(nvmlDeviceGetHandleByIndex(i)).decode() ) for i in device.getValidDeviceIdxsEnumerator() ])
```
On run
```bash
luke@spirit:/mnt/secondary/DeepFaceLab_Linux/scripts$ ./5_data_dst_extract_faces_S3FD_best_GPU.sh 
[0]
[61]
[(0, 'GeForce GTX 1070 Ti')]
```

In extractor.py
```python
from nnlib import nnlib
from joblib import Subprocessor
from interact import interact as io


print("Before class declaration and after import in Extractor")
print("All device idxs", nnlib.device.getAllDevicesIdxsList())
        
class ExtractSubprocessor(Subprocessor):
```
Output
```bash
Before class declaration
All device idxs [0]
Performing 1st pass...
Exception: Traceback (most recent call last):
```

When ``device_config = nnlib.DeviceConfig ( cpu_only=self.cpu_only, force_gpu_idx=self.device_idx, allow_growth=True)`` is called
```

```bash
Exception: Traceback (most recent call last):
  File "/mnt/secondary/DeepFaceLab_Linux/joblib/SubprocessorBase.py", line 58, in _subprocess_run
    self.on_initialize(client_dict)
  File "/mnt/secondary/DeepFaceLab_Linux/mainscripts/Extractor.py", line 59, in on_initialize
    device_config = nnlib.DeviceConfig ( cpu_only=self.cpu_only, force_gpu_idx=self.device_idx, allow_growth=True)
  File "/mnt/secondary/DeepFaceLab_Linux/nnlib/device.py", line 56, in __init__
    gpu_idx = force_gpu_idx if (force_gpu_idx >= 0 and device.isValidDeviceIdx(force_gpu_idx)) else device.getBestValidDeviceIdx() if not choose_worst_gpu else device.getWorstValidDeviceIdx()
  File "/mnt/secondary/DeepFaceLab_Linux/nnlib/device.py", line 201, in isValidDeviceIdx
    return idx in [*device.getValidDeviceIdxsEnumerator()]
  File "/mnt/secondary/DeepFaceLab_Linux/nnlib/device.py", line 86, in getValidDeviceIdxsEnumerator
    for gpu_idx in range(nvmlDeviceGetCount()):
  File "/mnt/secondary/DeepFaceLab_Linux/nnlib/pynvml.py", line 799, in nvmlDeviceGetCount
    _nvmlCheckReturn(ret)
  File "/mnt/secondary/DeepFaceLab_Linux/nnlib/pynvml.py", line 310, in _nvmlCheckReturn
    raise NVMLError(ret)
nnlib.pynvml.NVMLError_Uninitialized: Uninitialized
```

**Comment by iperov** [comment] 2019-03-13 12:15
it seems different windows and linux python behaviour with import in subprocesses :-\

**Comment by iperov** [comment] 2019-03-13 12:19
windows output:
```
Before class declaration and after import in Extractor
Performing 1st pass...
Before class declaration and after import in Extractor
Running on GeForce GTX 1060 6GB.
```

**Comment by iperov** [comment] 2019-03-13 12:25
linux python must call Extractor.py root when subprocess created.
If not - then we have to report a python bug ?
Can you make minimal reproduce with SubprocessorBase-like minimal logic?

**Comment by lbfs** [comment] 2019-03-13 12:48
I'll attempt to see if I can make a minimal reproduction of this, but I can't make any guarantees.

**Comment by lbfs** [comment] 2019-03-13 13:46
https://1drv.ms/u/s!AsIo0bqMjExjkWCK8fweTQD6Gb8O

I've reduced the test down to a few statements, It can probably be reduced further, but this is far as I can take it with my current understanding.

**Comment by iperov** [comment] 2019-03-13 13:48
O_O
this is not minimal.
I mean in one file.

**Comment by lbfs** [comment] 2019-03-13 13:49
I'll try going a bit further than. Ooops.

**Comment by iperov** [comment] 2019-03-13 13:50
dont use files from DFL at all.

**Comment by lbfs** [comment] 2019-03-13 15:04
```python
import traceback
from multiprocessing import Process

from pynvml import *
   
try:
    nvmlInit()
    print("Initalized correctly globally")
except:
    print("Failure to initalize globally")

def run_test():
    #Failure Case
    try:
        print("\nFailure case")
        print("Did not fail: ", nvmlDeviceGetCount())
    except:
        print(traceback.format_exc())

    #Now Fix It
    print("Forcing NVML Initialization (Only required on Linux!)")
    nvmlInit()
    print("Device Count", nvmlDeviceGetCount())

p = Process(target=run_test, args=() )
p.start()
p.join()


```
I was unable to figure out a way to replicate the issue without relying on pynvml, but this is the most minimal code I've gotten so far

**Comment by iperov** [comment] 2019-03-13 15:06
what output?

**Comment by lbfs** [comment] 2019-03-13 15:07
```bash
Initalized correctly globally

Failure case
Traceback (most recent call last):
  File "main.py", line 16, in run_test
    print("Did not fail: ", nvmlDeviceGetCount())
  File "/home/luke/Documents/BugTest/pynvml.py", line 799, in nvmlDeviceGetCount
    _nvmlCheckReturn(ret)
  File "/home/luke/Documents/BugTest/pynvml.py", line 310, in _nvmlCheckReturn
    raise NVMLError(ret)
pynvml.NVMLError_Uninitialized: Uninitialized

Forcing NVML Initialization (Only required on Linux!)
Device Count 1
```

**Comment by iperov** [comment] 2019-03-13 15:13
first run:
```
import traceback
from multiprocessing import Process

print("Root call, name: ", __name__)   

def run_test():
    print("run_test()")

if __name__ == "__main__":
    p = Process(target=run_test, args=() )
    p.start()
    p.join()
```

**Comment by iperov** [comment] 2019-03-13 15:15
then
```
import traceback
from multiprocessing import Process

from pynvml import *

print("Root call, name: ", __name__)   

try:
    print("call nvmlInit()")
    nvmlInit()
    print("success")
except:
    print("fail")

def run_test():
    print("run_test()")

if __name__ == "__main__":
    p = Process(target=run_test, args=() )
    p.start()
    p.join()
```

**Comment by iperov** [comment] 2019-03-13 15:15
post output both

**Comment by lbfs** [comment] 2019-03-13 15:21
First Test
```bash
(deepfacelab) luke@spirit:~/Documents/BugTest$ python3 test1.py 
Root call, name:  __main__
run_test()
```
Second Test
```
(deepfacelab) luke@spirit:~/Documents/BugTest$ python3 test2.py
Root call, name:  __main__
call nvmlInit()
success
run_test()
(deepfacelab) luke@spirit:~/Documents/BugTest$ 
```

**Comment by iperov** [comment] 2019-03-13 15:23
first test in windows:
```
Root call, name:  __main__
Root call, name:  __mp_main__
```
minimal reproduce - first test

**Comment by iperov** [comment] 2019-03-13 15:24
linux python must call root with `__mp_main__`
why it does not ?

**Comment by iperov** [comment] 2019-03-14 00:55
```
 multiprocessing.set_start_method(method)

    Set the method which should be used to start child processes. method can be 'fork', 'spawn' or 'forkserver'.

    Note that this should be called at most once, and it should be protected inside the if __name__ == '__main__' clause of the main module.
```

**Comment by iperov** [comment] 2019-03-14 00:56
test please issue with

main.py
```
if __name__ == "__main__":
    import multiprocessing
    multiprocessing.set_start_method("spawn")
```

**Comment by lbfs** [comment] 2019-03-14 01:03
Added that to main.py and the issue is still fixed, I didn't realize that function was only supposed to be called once. 
:)

**Comment by iperov** [comment] 2019-03-14 01:07
i just read the help :)

ok I will add this fix to main repo.

**Comment by lbfs** [comment] 2019-03-14 01:07
Cool, I'm glad we solved it

**Closed** 2019-03-24 11:29 UTC
